# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - geradordeapostila

on:
  push:
    branches:
      - with-frontend
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Create Streamlit secrets.toml
        run: |
          mkdir -p .streamlit
          echo "[auth]
          redirect_uri = \"${{ secrets.REDIRECT_URI }}\"
          cookie_secret = \"${{ secrets.COOKIE_SECRET }}\"
          client_id = \"${{ secrets.CLIENT_ID }}\"
          client_secret = \"${{ secrets.CLIENT_SECRET }}\"
          server_metadata_url = \"${{ secrets.SERVER_METADATA_URL }}\"
          " > .streamlit/secrets.toml

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_94FB0D5A2B394A2A96EBEB6426659009 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3DCDDD62F82E4369B5EC5F7B359C0D6B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C1B0003D8F6D462783EC8407EA1F51A6 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'geradordeapostila'
          slot-name: 'Production'
          